### ISSUE TITLE
docker run finish wirh syntax error  near "CONSTRAINT"

### ISSUE THREAD

**Issue by tootai** [elokapina/middleman#35] opened 2024-07-22 17:41 UTC
Hi,

I install the docker container and setup config.yaml in ~ docker/support_bot/data
Hereunder the output of docker run

$ docker run -v ${PWD}/docker/support_bot/data/config.yaml:/config/config.yaml:ro -v ${PWD}/docker/support_bot/data:/data --name support_bot murlock1000/support_bot
Starting grpc loop
Starting main loop
2024-07-22 17:16:56,830 | support_bot.storage [INFO] Performing initial database setup...
2024-07-22 17:16:56,959 | support_bot.storage [INFO] Database setup complete
2024-07-22 17:16:56,959 | support_bot.storage [INFO] Migrating the database from v0 to v1...
2024-07-22 17:16:57,058 | support_bot.storage [INFO] Database migrated to v1
2024-07-22 17:16:57,059 | support_bot.storage [INFO] Migrating the database from v1 to v2...
2024-07-22 17:16:57,250 | support_bot.storage [INFO] Database migrated to v2
2024-07-22 17:16:57,250 | support_bot.storage [INFO] Migrating the database from v2 to v3...
2024-07-22 17:16:57,375 | support_bot.storage [INFO] Database migrated to v3
2024-07-22 17:16:57,375 | support_bot.storage [INFO] Migrating the database from v3 to v4...
2024-07-22 17:16:57,534 | support_bot.storage [INFO] Database migrated to v4
2024-07-22 17:16:57,534 | support_bot.storage [INFO] Migrating the database from v4 to v5...
2024-07-22 17:16:57,675 | support_bot.storage [INFO] Database migrated to v5
2024-07-22 17:16:57,675 | support_bot.storage [INFO] Migrating the database from v5 to v6...
2024-07-22 17:16:58,467 | support_bot.storage [INFO] Database migrated to v6
2024-07-22 17:16:58,467 | support_bot.storage [INFO] Migrating the database from v6 to v7...
Main loop exited: near "CONSTRAINT": syntax error
2024-07-22 17:16:58,517 | grpc_server.server [INFO] Closing grpc server

It's running on a Debian 12, synapse works perfectly.

Thanks for any hint

**Comment by jaywink** [comment] 2024-09-14 22:11
Sorry, extremely slow response time... I somehow missed this earlier.

So this seems somewhat odd since Middleman has only 5 migrations (https://github.com/elokapina/middleman/tree/master/middleman/migrations). Are you running a fork? Then the issue is probably in the migration number 7, which has some invalid SQL.

Closing as this doesn't seem an issue in this Middleman version.

**Closed as completed by jaywink** 2024-09-14 22:11 UTC
